-- AlterTable
ALTER TABLE "ShoppingCart" ADD COLUMN     "extraFee" DOUBLE PRECISION NOT NULL DEFAULT 0.00,
ADD COLUMN     "rentalPrice" DOUBLE PRECISION NOT NULL DEFAULT 0.00,
ADD COLUMN     "shippingFee" DOUBLE PRECISION NOT NULL DEFAULT 4.99,
ALTER COLUMN "totalPrice" SET DEFAULT 4.99;
