import Head from 'next/head'
import Header from '../components/header'
import Image from 'next/image'
import Link from 'next/link'
import homepage_banner from '../images/homepage1.jpg'
import { useState } from 'react'

export default function Home() {
  const [searchTerm, setSearchTerm] = useState('')
  return (
    <div>
      <Head>
        <title>BeGentle! Instrumentenverleih</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="grid grid-cols-1 py-8 px-8 place-items-center">
        <div
          className="h-max w-full bg-cover bg-center grid grid-cols-1 place-items-center border-solid border-b-4 border-b-cl2"
          id="Banner"
        >
          <div className="-z-10 overflow-hidden h-max w-max bg-gradient-to-b from-black to-white bg-cover">
            <Image
              src={homepage_banner}
              alt=""
              layout="fill"
              className="-z-10"
              objectFit="cover"
              objectpostion="center"
            />
          </div>

          <div className="z-1 text-left w-5/6 text-cl1">
            <div className="text-7xl font-gabriela py-4">
              Musik beginnt mit einem guten Instrument.
            </div>
            <div className="text-3xl py-2">
              Lass dich auf unsere Violinen ein und spiel nie mehr die letzte
              Geige. Unverbindlich. Individuell. Wie für dich gemacht.
            </div>
          </div>
          <div className="z-1 w-5/6 text-cl1 grid grid-cols-1 place-items-center py-16">
            <div>
              <input
                className="h-14 w-[600px] pl-4 bg-cl4 border-solid border-r-0 border-2 border-cl1 rounded-l-xl text-xl outline-none"
                type="text"
                placeholder="Welches Instrument suchst du?"
                onChange={(e) => setSearchTerm(e.target.value)}
              />
              <Link href={`/search?term=${searchTerm}`}>
                <button className="bg-cl1 text-cl2 font-gabriela h-14 w-[200px] rounded-r-xl text-2xl">
                  Suchen
                </button>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
