import Head from 'next/head'
import Header from '../components/header'
import Image from 'next/image'
import Link from 'next/link'
import Product from '../components/product'
import Footer from '../components/footer'
import { useState } from 'react'

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>BeGentle! Instrumentenverleih</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=' bg-cl6'>
        <div>
            Kunden Login
        </div>
        <div className="pl-4 pt-4 pb-1 text-cl1 font-light">
              E-Mail:
            </div>
            <input
              className={inputCss}
              defaultValue={email}
              onChange={(e) => setEmail(e.target.value)}
            />
      </div>
      
        
        <Footer />
    </div>
  )
}