import Head from 'next/head'
import Header from '../components/header'
import Link from 'next/link'
import Product from '../components/product'
import Footer from '../components/footer'
import Image from 'next/image'
import { useState } from 'react'

export default function Home({ props, term }) {
  var searchResult
  if(props.length != 0){
    const listItems = props.map((item) => <Product key={item.id}>{item}</Product>)
    searchResult = (
      <ul className="w-5/6 max-w-7xl h-max grid grid-cols-1 md:grid-cols-2 2xl:grid-cols-3 place-items-center py-8">
        {listItems}
        <li className="md:col-span-2 2xl:col-span-3 border-solid border-2 border-cl1 bg-cl2 rounded-xl w-5/6 grid grid-cols-1 place-items-center">
          <a className='w-5/6 py-6 text-2xl font-gabriela text-cl1 text-center'>Das darf doch nicht wahr sein. Mehr haben wir leider nicht.</a>
          <p className='w-4/6 text-center font-gabriela'>Wir suchen unsere Instrumente liebevoll aus. Bei uns gilt Klasse statt Masse. Aber vielleicht findest du etwas bei den anderen Instrumenten.</p>
          <div className="h-[170px] py-10 w-full grid grid-cols-1 rounded-xl place-content-center overflow-hidden">
            <Image
              src='/icons/sad.png'
              alt="Leider gibt es zu diesem Instrument kein Bild"
              width={4000}
              height={4000}
              className="rounded-xl"
              layout="responsive"
              objectFit="contain"
            />
          </div>
        </li>
      </ul>
    )
  } else {
    searchResult = (
      <ul className="w-5/6 max-w-7xl h-max grid grid-cols-1 md:grid-cols-2 2xl:grid-cols-3 place-items-center py-8">
        <li className="md:col-span-2 2xl:col-span-3 border-solid border-2 border-cl1 bg-cl2 rounded-xl w-5/6 grid grid-cols-1 place-items-center">
          <a className='w-5/6 py-6 text-2xl font-gabriela text-cl1 text-center'>Das darf doch nicht wahr sein. Wir haben nicht was du suchst.</a>
          <p className='w-4/6 text-center font-gabriela'>Wir suchen unsere Instrumente liebevoll aus. Bei uns gilt Klasse statt Masse. Aber vielleicht findest du etwas bei den anderen Instrumenten.</p>
          <div className="h-[170px] py-10 w-full grid grid-cols-1 rounded-xl place-content-center overflow-hidden">
            <Image
              src='/icons/sad.png'
              alt="Leider gibt es zu diesem Instrument kein Bild"
              width={4000}
              height={4000}
              className="rounded-xl"
              layout="responsive"
              objectFit="contain"
            />
          </div>
        </li>
      </ul>
    )
  }
  
  const [searchTerm, setSearchTerm] = useState(term)
  return (
    <div>
      <Head>
        <title>BeGentle! Instrumentenverleih</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 place-items-center">
        <div
          className="w-screen min-h-screen bg-cl4 flex flex-col"
          id="page-content"
        >
          <Header />
          <div className="z-1 w-screen bg-cl3 rounded-b-xl flex drop-shadow-lg justify-center h-max">
            <div className="w-5/6 flex justify-between">
              <div className="w-1/2 font-gabriela text-2xl text-cl1 py-6">
                Deine Suchergebnisse
              </div>
              <div className="w-max h-full text-cl1 grid grid-cols-1 place-items-center">
                <div>
                  <input
                    className="h-12 xl:w-[400px] sm:w-[200px] w-full pl-4 bg-cl4 border-solid border-2 border-cl1 rounded-t-2xl sm:rounded-t-none sm:rounded-l-2xl text-lg outline-none"
                    type="text"
                    placeholder={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                  />
                  <Link href={`/search?term=${searchTerm}`}>
                    <button className="bg-cl1 text-cl2 font-gabriela h-12 xl:w-[100px] sm:w-[150px] w-full rounded-b-2xl sm:rounded-b-none sm:rounded-r-2xl text-xl">
                      Suchen
                    </button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
          <div className="flex-grow w-screen flex justify-center">
            {searchResult}
          </div>

          <Footer />
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps(context) {
  const term = context.query.term
  const res = await fetch(`http://localhost:3000/api/search?name=${term}`)
  let data
  if (res.status == 404) {
    data = []
  } else {
    data = await res.json()
  }
  console.log(data)
  return {
    props: {
      props: data,
      term: term,
    },
  }
}
